### ISSUE TITLE
Tecnologias de Software

### ISSUE THREAD

**Issue by CpSolanoL** [camiloGonzalez96/plataforma-de-boleteria-bit-bang#1]
Frontend:

- React 
- Bootstrap

Backend:

- Node.JS - Express
- Heroku
- Heroku-postgresql
- PostgreSQL
- pgAdmin

IC/DC:
- GitHub Actions

Control de versiones:
- GitHub

Control de metodología:
- ZenHub

Manejo contenedor
- Docker

**Comment by CpSolanoL** [comment]
![Error consulta boletas en auditoria](https://user-images.githubusercontent.com/53833246/109694388-c0633e00-7b58-11eb-8b25-096544e4fa6a.JPG)

**Comment by CpSolanoL** [comment]
gdfg

**Comment by camiloGonzalez96** [comment]
se realiza una reunión de sprint planning
![sprint planning.png](https://images.zenhubusercontent.com/5f41d78586180d02dc148ee5/fb560a69-00ed-426b-9d53-cb21c82b8efe)
