### ISSUE TITLE
Levantamiento de Requerimientos

### ISSUE THREAD

**Issue by camiloGonzalez96** [camiloGonzalez96/plataforma-de-boleteria-bit-bang#2]
Analizamos el proyecto planteado y levantamos requerimientos, con los que definiremos las historias de usuario

**Comment by CpSolanoL** [comment]
Doc:
https://docs.google.com/document/d/1mWapNe3caf3RTxxI3Im6BYGc20sB42Aqr0_Ji27i3Ho/edit
